### ISSUE TITLE
代码块内的数学公式被解释为数学公式

### ISSUE THREAD

**Issue by YuxinZhaozyx** [ikeq/hexo-filter-mathjax-ssr#2]
代码块内的数学公式被错误地解释为数学公式
版本： hexo-filter-mathjax-ssr@0.1.1

**markdown：**
`````
```
$$
\alpha = 1
$$
```

`$\alpha=1$`

`````

显示结果：

![image](https://user-images.githubusercontent.com/32972764/66035072-0cade700-e53d-11e9-919e-e298bdc1ef9a.png)

**Comment by ikeq** [comment]
因为代码块里匹配到了 blockMath，不太好处理，只能通过标记区分开，代码块里不要使用 blockMath 的符号。另外如果只是为了演示数学公式，并不需要带上块级符号啊。

我是这样配的：
```yml
mathjax:
  inlineQuote: '@'
  blockQuote: ['```tex', '```']
```

演示就用别的符号，或者不带符号，因为 ```tex 本身就与代码块冲突（甩锅）。
